### PR TITLE
Add Debian GNU/Linux logo

### PR DESCRIPTION
**Pull request by Billy02357**
Added logos/debian.h for Debian GNU/Linux

### CODE REVIEW

**Comment by PalanixYT** [comment]
hmmm, the neofetch version has a white spiral with red accents and red texts. Could you add that? see mint logo for more help. Ofc i could do it too if you don't want to

**Comment by Billy02357** [comment]
i'm not sure how to make it with different colors, feel free to add it yourself or if you don't then I'll try to look into it

**Comment by PalanixYT** [comment]
ok i'll do it

**Comment by PalanixYT** [comment]
yeah i did it now, anyways, thanks for your help.

**Pull request closed without merging**
