### PR TITLE
Add 5 new logos

### PR DESCRIPTION
**Pull request by Billy02357**
- Added Fedora logo
- Add FreeBSD logo
- Add Guix logo
- Add Hyperbola logo
- Added Pop!OS logo

### CODE REVIEW

**Comment by PalanixYT** [comment]
Thank you! Could you pull the updates to your fork? Otherwise they will be overwritten

**Comment by Billy02357** [comment]
You mean I run `git pull` ?
Tells me already up to date

**Comment by PalanixYT** [comment]
No. Your fork of wayfetch is behind my fork

**Comment by Billy02357** [comment]
I'm sorry I never forked anything ever on github, I didnt pull it but just made the changes you commited, woudl that work? sorry again

**Comment by PalanixYT** [comment]
Well, I really meant you should make a PR and pull in all changes 
https://medium.com/@sahoosunilkumar/how-to-update-a-fork-in-git-95a7daadc14e

**Comment by Billy02357** [comment]
Done. Thanks.

**Comment by PalanixYT** [comment]
I think it would be best to make a new pr

**Comment by PalanixYT** [comment]
Nvm

**Pull request merged**
