### PR TITLE
Added time -p command to README

### PR DESCRIPTION
**Pull request by Billy02357**

### CODE REVIEW

**Comment by PalanixYT** [comment]
to have more consistency, could you also run the hyperfine command?

**Comment by PalanixYT** [comment]
oops accidentally closed pr

**Comment by Billy02357** [comment]
"hyperfine" is not a command in neofetch as far as I know. What do you mean?

**Comment by PalanixYT** [comment]
hyperfine is cli utility to test programs on their speed

**Comment by Billy02357** [comment]
Done :^)

**Pull request merged**
